services:
  oracle-db:
    container_name: oracle-xe
    build: ./SQL
    environment:
      - ORACLE_SID=xe
    volumes:
      - oracle-database:/opt/oracle/oradata
    ports:
      - 1521:1521
      - 5500:5500
    restart: always

  mongodb:
    container_name: mongodb
    build: ./MongoDB 
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    restart: always

volumes:
  oracle-database:
    name: oracle_database
  mongodb-data:
    name: mongodb_data